tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-secondary": "#003543",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb68b",
        "surface": "#131316",
        "primary-fixed-dim": "#c9bfff",
        "inverse-surface": "#e4e1e6",
        "surface-dim": "#131316",
        "on-surface-variant": "#c9c4d7",
        "on-tertiary-container": "#ffc9ab",
        "on-surface": "#e4e1e6",
        "on-secondary-fixed": "#001f28",
        "surface-container-lowest": "#0e0e11",
        "secondary": "#a6e6ff",
        "outline-variant": "#484554",
        "on-secondary-container": "#00566b",
        "on-primary-fixed-variant": "#4500d8",
        "on-tertiary": "#522300",
        "tertiary-container": "#954500",
        "on-tertiary-fixed": "#321300",
        "surface-container-high": "#2a2a2d",
        "surface-container-low": "#1b1b1e",
        "surface-container": "#1f1f22",
        "secondary-container": "#14d1ff",
        "surface-variant": "#353438",
        "inverse-on-surface": "#303033",
        "tertiary": "#ffb68b",
        "on-secondary-fixed-variant": "#004e60",
        "surface-container-highest": "#353438",
        "primary-fixed": "#e5deff",
        "surface-bright": "#39393c",
        "on-primary-fixed": "#1b0063",
        "tertiary-fixed": "#ffdbc8",
        "secondary-fixed": "#b7eaff",
        "outline": "#938ea0",
        "inverse-primary": "#5d2ffa",
        "primary-container": "#5a2af8",
        "error": "#ffb4ab",
        "surface-tint": "#c9bfff",
        "background": "#131316",
        "secondary-fixed-dim": "#4cd6ff",
        "primary": "#5D3FD3",
        "on-primary-container": "#d7ceff",
        "on-error": "#690005",
        "on-background": "#e4e1e6",
        "on-tertiary-fixed-variant": "#743400",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
}
